# Site settings
title: flobeck
email: firstname DOT lastname91 AT me DOT com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: 127.0.0.1:4000 #"http://yourdomain.com" # the base hostname & protocol for your site
permalink: /:title

#twitter_username: jekyllrb
github_username:  flobeck

# Build settings
markdown: kramdown
